import Link from '@/node_modules/next/link';
import type { Metadata } from "next";
import React from 'react'



export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};
export default function AboutLayout({children}) {
  return (
      
    <div>
        <nav className='mt-6 mb-6'>
        <ul className="flex gap-6">
            <li><Link href="/about/mission">Mission</Link> </li>
            <li><Link href="/about/vission">Vission</Link></li>
          </ul>
         </nav>
        {children}
    </div>
  )
}
