import Link from "@/node_modules/next/link";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Modal from "./components/Modal";

import "./globals.css";
import BasicModal from "./components/BasicModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="p-6">
      <body className={inter.className}>
        <nav>
          <ul className="flex gap-6">
            <li><Link href="/">Home</Link> </li>
            <li><Link href="/about">About</Link></li>
            <li><Link href="/blogs">Blogs</Link></li>
            <li><Link href="/post">Posts</Link></li>
            <li><Link href="/save">Save</Link></li>
          
          </ul>
         </nav>
        <hr/> 
        {children}
        <Modal/>
        <BasicModal/>
        </body>
    </html>
  );
}
